-- liquibase formatted sql

-- changeset Marsel:1759914792855-1
CREATE SEQUENCE IF NOT EXISTS product_seq START WITH 1 INCREMENT BY 1;

-- changeset Marsel:1759914792855-2
CREATE SEQUENCE IF NOT EXISTS role_seq START WITH 1 INCREMENT BY 50;

-- changeset Marsel:1759914792855-3
CREATE TABLE blacklist_registry
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type             VARCHAR(30)                             NOT NULL,
    document_id               VARCHAR(50)                             NOT NULL,
    blacklisted_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reason                    VARCHAR(255),
    blacklist_expiration_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_blacklist_registry PRIMARY KEY (id)
);

-- changeset Marsel:1759914792855-4
CREATE TABLE client_products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id  VARCHAR(255),
    product_id VARCHAR(255),
    open_date  date,
    close_date date,
    status     VARCHAR(255),
    CONSTRAINT pk_client_products PRIMARY KEY (id)
);

-- changeset Marsel:1759914792855-5
CREATE TABLE clients
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id       VARCHAR(255)                            NOT NULL,
    user_id         BIGINT,
    first_name      VARCHAR(255),
    middle_name     VARCHAR(255),
    last_name       VARCHAR(255),
    date_of_birth   date,
    document_type   VARCHAR(255),
    document_id     VARCHAR(255),
    document_prefix VARCHAR(255),
    document_suffix VARCHAR(255),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

-- changeset Marsel:1759914792855-6
CREATE TABLE products
(
    id          BIGINT       NOT NULL,
    name        VARCHAR(255),
    key         VARCHAR(255) NOT NULL,
    create_date date,
    product_id  VARCHAR(255) NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

-- changeset Marsel:1759914792855-7
CREATE TABLE role
(
    id   BIGINT NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset Marsel:1759914792855-8
CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

-- changeset Marsel:1759914792855-9
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset Marsel:1759914792855-10
ALTER TABLE blacklist_registry
    ADD CONSTRAINT uc_blacklist_registry_documentid UNIQUE (document_id);

-- changeset Marsel:1759914792855-11
ALTER TABLE clients
    ADD CONSTRAINT uc_clients_clientid UNIQUE (client_id);

-- changeset Marsel:1759914792855-12
ALTER TABLE products
    ADD CONSTRAINT uc_products_productid UNIQUE (product_id);

-- changeset Marsel:1759914792855-13
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset Marsel:1759914792855-14
ALTER TABLE users
    ADD CONSTRAINT uc_users_login UNIQUE (login);

-- changeset Marsel:1759914792855-15
ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (id);

-- changeset Marsel:1759914792855-16
ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

