-- liquibase formatted sql

-- changeset Marsel:1759059641291-1
CREATE TABLE error_log
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    service_name      VARCHAR(255),
    timestamp         TIMESTAMP WITHOUT TIME ZONE,
    method_signature  VARCHAR(2000),
    stack_trace       OID,
    exception_message VARCHAR(2000),
    payload           OID,
    CONSTRAINT pk_error_log PRIMARY KEY (id)
);

