-- liquibase formatted sql

-- changeset Marsel:1758725860123-1
CREATE TABLE accounts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id     VARCHAR(255),
    product_id    VARCHAR(255),
    balance       DECIMAL(19, 2),
    interest_rate DOUBLE PRECISION,
    is_recalc     BOOLEAN,
    card_exist    BOOLEAN,
    status        VARCHAR(255),
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

-- changeset Marsel:1758725860123-2
CREATE TABLE cards
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id     BIGINT,
    card_id        VARCHAR(255),
    payment_system VARCHAR(255),
    status         VARCHAR(255),
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

-- changeset Marsel:1758725860123-3
CREATE TABLE payments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id   BIGINT,
    payment_date TIMESTAMP WITHOUT TIME ZONE,
    amount       DECIMAL(19, 2),
    is_credit    BOOLEAN,
    payed_at     TIMESTAMP WITHOUT TIME ZONE,
    type         VARCHAR(255),
    expired      BOOLEAN,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

-- changeset Marsel:1758725860123-4
CREATE TABLE transactions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id BIGINT,
    card_id    BIGINT,
    type       SMALLINT,
    amount     DECIMAL(19, 2),
    status     VARCHAR(255),
    timestamp  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

